# Generated by Django 4.2.2 on 2023-09-02 05:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import onedaytwogether.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('Image', models.FileField(blank=True, upload_to=onedaytwogether.models.Destination_directory_path, validators=[onedaytwogether.models.validate_file_extension])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tour_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.CharField(max_length=30)),
                ('Image', models.FileField(blank=True, upload_to=onedaytwogether.models.User_Profile_directory_path, validators=[onedaytwogether.models.validate_file_extension])),
                ('tel', models.CharField(max_length=30)),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('avartar', models.FileField(blank=True, upload_to=onedaytwogether.models.User_Profile_directory_path, validators=[onedaytwogether.models.validate_file_extension])),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Femail', 'Female')], max_length=7)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=150)),
                ('tel', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('Users_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schedule', models.DateField()),
                ('Destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onedaytwogether.destination')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
