# Generated by Django 4.2.2 on 2023-09-02 05:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onedaytwogether', '0002_destination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='address',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
