# Generated by Django 4.2.2 on 2023-09-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onedaytwogether', '0003_destination_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='Users_ID',
            new_name='Username',
        ),
    ]
