# Generated by Django 4.2.2 on 2023-09-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onedaytwogether', '0004_rename_users_id_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='Username',
            new_name='Users',
        ),
    ]
