# Generated by Django 4.2.2 on 2023-09-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onedaytwogether', '0005_rename_username_user_profile_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='avartar',
            new_name='avatar',
        ),
    ]
