# Generated by Django 4.2.2 on 2023-09-03 07:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import onedaytwogether.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onedaytwogether', '0006_rename_avartar_user_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=30)),
                ('Image', models.FileField(blank=True, upload_to=onedaytwogether.models.Product_directory_path, validators=[onedaytwogether.models.validate_file_extension])),
                ('Quantity', models.IntegerField()),
                ('Original_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('New_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Product_Type', models.CharField(max_length=30)),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onedaytwogether.destination')),
                ('Schedule_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onedaytwogether.schedule')),
                ('Tour_Team_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onedaytwogether.tour_team')),
                ('User_Profile_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onedaytwogether.user_profile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateField()),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onedaytwogether.shop')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
