# Generated by Django 4.2.2 on 2023-09-07 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onedaytwogether', '0009_alter_user_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Phone_Number', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=100)),
                ('Details', models.CharField(max_length=200)),
                ('Destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onedaytwogether.destination')),
                ('Schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onedaytwogether.schedule')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
