# Generated by Django 4.2.2 on 2023-09-08 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import onedaytwogether.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onedaytwogether', '0011_alter_shop_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, upload_to=onedaytwogether.models.Product_directory_path, validators=[onedaytwogether.models.validate_file_extension])),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Sized', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=7)),
                ('Quantity', models.IntegerField()),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onedaytwogether.shop')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
