# Generated by Django 4.2.2 on 2023-09-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedaytwogether', '0014_alter_user_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Sized',
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
