# Generated by Django 4.2.2 on 2023-09-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onedaytwogether', '0016_contact_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
