# Generated by Django 4.2.2 on 2023-09-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedaytwogether', '0018_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Memebers',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
