# Generated by Django 4.2.2 on 2023-09-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onedaytwogether', '0019_contact_memebers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Memebers',
            new_name='Members',
        ),
    ]
