# Generated by Django 4.2.2 on 2023-09-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedaytwogether', '0020_rename_memebers_contact_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Details',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
